### ISSUE TITLE
Unable to change permission of android files

### ISSUE THREAD

**Issue by verymilan** [wdehoog/sailfish-bacon-images#1]
Hi there,

guess something changed since the vgrade port - `/android/media/0/Music` did not match anymore.
So i tried to symlink from `/storage/sdcard0/Music` but the permissions do not fit `root:sdcard_r`.
So i've added nemo to the group so it can actually read it but no, it can't.
Okey, so i decided to simply change the filepermissions on a way that it wouldn't break when i move back to Android and nemo can read them but no:
A simple chown or chmod just enters but don't change anything on the folder.
When i try to alter the files recursive, i get this:
```
chown: changing ownership of `/storage/sdcard0/Music/track.mp3': Interrupted system call
```

Update: I tested in `nemo/`, it works there. Odd.

Kind regards and thanks for your work. :)

**Comment by wdehoog** [comment]
I am not aware of any change on this issue. I am just using the repos from mer-hybris to build the image. It looks like a lot of android files are owned by media_rw.media_rw so adding user nemo to the  media_rw group might help you. 

How did you mount? I see no problems when doing 'devel-su chown'.

**Comment by verymilan** [comment]
No, as i wrote, it appears to be `root:sdcard_r` (at least this is what sailfish understands).
And adding nemo to the group did sadly not help.
```
[root@Sailfish Music]# ls /storage/sdcard0/ -l
total 3699332
-rw-rw----  1 root sdcard_r 819532755 Jan  4 17:29 some.mp3
drwxrwx---  2 root sdcard_r      4096 Sep 27 10:07 APG
drwxrwx---  2 root sdcard_r      4096 Sep 20  1971 Alarms
-rw-rw----  1 root sdcard_r 326199446 Jan  4 17:28 some.mp3
drwxrwx--x  4 root sdcard_r      4096 Sep 30 14:32 Android
drwxrwx---  3 root sdcard_r      4096 Oct 31 09:50 Browser
drwxrwx---  2 root sdcard_r      4096 Sep 27 10:14 CalendarEvents
drwxrwx---  2 root sdcard_r      4096 Jan 18 16:21 Conversations
drwxrwx---  6 root sdcard_r      4096 Oct 30 21:37 DCIM
drwxrwx---  2 root sdcard_r      4096 Dec 29 15:16 Download
...
```

Also adding nemo to your mentioned group did not help:

```
[root@Sailfish Music]# gpasswd -a  nemo media_rw         
Adding user nemo to group media_rw
[root@Sailfish Music]# su nemo
NOTICE: Env value ignored HYBRIS_LD_LIBRARY_PATH=/usr/libexec/droid-hybris/system/lib:/vendor/lib:/system/lib
[nemo@Sailfish]$ cd /storage/sdcard0/
bash: cd: /storage/sdcard0/: Permission denied
```
Well yeah, wrong group in that case but hey, just to make this answer complete. :) 

I did not mount anything - i installed it over my existing installation:

* factory reset
* install cm12
* install sfos

...and use ssh for managing files and packages.

**Comment by wdehoog** [comment]
Sorry. Never looked at those directories. I do this: https://sailfish-for-opo.tchncs.de/tricks-and-fixes#android-share.

No idea what this /storage is supposed to do. For me it is different:
/storage/sdcard0 -> /storage/emulated/legacy
/storage/emulated/legacy -> /mnt/shell/emulated/0 which is empty

**Comment by verymilan** [comment]
Yes, this is a symlink and points to the actual files.
Aww i actually wrote this page but didn't read close enough by my self. -.-
I did not created the `/android` mountpoint, i just overread this because i did not see why i should mount files which are there anyway (you see what i mean?).

Sorry for wasting your time.
