### ISSUE TITLE
version sailfish 3.1.0.11

### ISSUE THREAD

**Issue by geminis65** [wdehoog/sailfish-bacon-images#11]
good afternoon, one question: you are not going to upload the sailfish 3.1.0.11.release image a greeting

**Comment by wdehoog** [comment]
I am sorry but I do not have one. I tried to build it but the UI stutters and crashes. I am afraid the problem is too complex for me. Maybe I'll give it another try in the future.

**Comment by htot** [comment]
Help wanted / Won't fix?

**Comment by xsetiadi** [comment]
please build next version if you have time sir

Regards, from Indonesia

**Comment by wdehoog** [comment]
I just released 3.2.0.12
