### ISSUE TITLE
sailfish 3.2.0.12

### ISSUE THREAD

**Issue by jesus6505** [wdehoog/sailfish-bacon-images#12]
good, I tried to install the latest version of sailfish 3.2.0.12 following the steps you put to receive ota and I am blocked.on the page the latest version is the 3.1.0.12.  To install the latest version without you have uploaded it is necessary to install something extra or a special command? a greeting(I have a oneplus one)

**Comment by wdehoog** [comment]
There is no 3.2.01.12 'testing' target. I have built some stuff on 'dev' but I don't have time nor motivation now to actually test it. Sorry.

**Comment by jesus6505** [comment]
good, thank you very much for your effort.what you have done can be installed? -If so you can send me the zip file to install it and see how it goes?.a greeting.

**Comment by wdehoog** [comment]
I have updated the 'testing' repo and released a beta-1 for 3.2.0.12.

**Comment by jesus6505** [comment]
Okay. Thank you very much.

**Comment by jesus6505** [comment]
hello i have updated to version 3.2.1.20 through the terminal and when i restart the sound you can not download or upload and you can not see images on the camera, ie the camera works, the zoom too but you can not see anything that can be recorded.you know how you can fix this.

**Comment by wdehoog** [comment]
Which repos did you use to update? I have done nothing for version 3.2.1.20 so I expect only the jolla ones are up-to-date. The testing repo is still at 3.2.0.12. 

Sorry but I am not going to spend time on version 3.2.1.20.

**Comment by jesus6505** [comment]
http://repo.merproject.org/obs/nemo:/testing:/hw:/oneplus:/bacon/sailfishos_3.2.1.20/ http://repo.merproject.org/obs/nemo:/testing:/hw:/common/sailfishos_3.2.1.20.
you can tell me how to install this package, it's the only one that when you install the 3.2.1.20 uninstall 
droid-config-bacon-policy-settings;0.0.2+master.20191116081709.45.g2d3a013-1.19.1.jolla;armv7hl
Sorry for the inconvenience. Thank you very much.

**Comment by wdehoog** [comment]
If you check then you will notice this one does not exist: http://repo.merproject.org/obs/nemo:/testing:/hw:/oneplus:/bacon/sailfishos_3.2.1.20/
There is no device specific repo for 3.2.1.20 for the oneplus one. 

For the previous version a repo does exist: http://repo.merproject.org/obs/nemo:/testing:/hw:/oneplus:/bacon/sailfishos_3.1.0.12/

**Comment by jesus6505** [comment]
a question, then if you don't put a new release of version 3.2.1.20 you can't upgrade from the terminal with pkcon refresh; version --dup?

**Comment by jesus6505** [comment]
a question, then if you don't put a new release of version 3.2.1.20 you can't upgrade from the terminal with pkcon refresh; version --dup?

**Comment by wdehoog** [comment]
Correct. A device specific repo must be available for the same version as the OS.

**Comment by jesus6505** [comment]
Okay. Thank you very much.
