### ISSUE TITLE
The custom CM 12.1 ROM is getting stuck at boot animation

### ISSUE THREAD

**Issue by NazimLeulmi** [wdehoog/sailfish-bacon-images#13]
I tried to install CM 12.1 ( another version than the one provided ) then flash sailfish os . The camera didn't work . I read that I should use your custom CM 12.1 to fix the camera issue . I tried installing your custom CM 12.1 a couple of times . It keeps getting stuck at boot animation

**Comment by wdehoog** [comment]
Maybe this helps: https://github.com/wdehoog/sailfish-bacon-images/issues/6#issuecomment-473003855

**Comment by NazimLeulmi** [comment]
@wdehoog thank you! the installation went smoothly after flashing the stock rom . The camera is working now :dancing_men:
