### ISSUE TITLE
vibrator not working on 3.4.0.24

### ISSUE THREAD

**Issue by sailorhub77** [wdehoog/sailfish-bacon-images#18]
I just noticed a lack of haptic feedback after upgrading to 3.4.0.24. And when I tried the vibration test on csd, it turned out the motor is not working.

Again, this is not important for me to survive. Just thought I'd add it while I'm here.

**Comment by wdehoog** [comment]
This should be fixed by https://github.com/mer-hybris/android_system_core/commit/5625e527ae048fbf41605705c3cb690b94206519  

Maybe I'll update the testing repo.

**Comment by sailorhub77** [comment]
Wow, you are fast. Patching the /init.rc file did the trick. The motor is back in business! Thanks so much for your help.

**Comment by wdehoog** [comment]
The updated droid-hal-bacon in the testing repository fixes this issue.
