### ISSUE TITLE
mail broken on 3.4.0.24

### ISSUE THREAD

**Issue by sailorhub77** [wdehoog/sailfish-bacon-images#19]
I think I came across a new problem this morning. My mail accounts were suspiciously quiet. So, I checked only to find they hadn't been updated since the upgrade. Forcing an mail sync just produced an endless "waiting icon" (that rotating circle). So, I deleted my mail account and established a new one. However, I could not set it up since account manager complained about a non-working receiving server. Of course I checked, the account works well on my desktop pc (using exactly the same credential, servers, ports).

**Comment by wdehoog** [comment]
Without logs I cannot be of much help. If I ask the wizards on IRC (#sailfishos-porters) they need full logs. So ALL lines starting from boot including those during the test (create account and read email). I think journal is enough (no dmesg nor logcat). Best is using one of those pastebin alike services.

**Comment by wdehoog** [comment]
I added an email account (General) and it seems to work well. 

My phone currently runs a test build with the latest libhybris and an updated droid-hal-bacon. The rest is not updated. It is unlikely that libhybris is the cause so maybe you could try updating droid-hal-bacon. I have just updated the testing repository so you could give it a try.

As for libhybris updating that is problematic. When my phone boots the screen is sluggish, some icons are not shown and logcat is full of EGL errors. After restarting lipstick (```systemctl --user restart lipstick```) all seems well. Sometimes I have to restart lipstick multiple times. Therefore I did not update libhybris in testing.

**Comment by sailorhub77** [comment]
I am surprised you were able to add an email account (General). After deleting one of my accounts, I am unable to set it up again. Neither can I set up an account with a different mail provider. Both mail servers are up and responding on the respective ports (tested with nmap on the phone).

I have updated droid-hal-bacon (thanks for that, it works well!) through zypper ref; zypper up. However, the problem persists.

I am not familiar with pastebin, so here are a few journalctl lines produced after hitting "accept" in the "adding email account (general)" dialogue. Btw, the screen dialogue reads "Problem with configuration  Could not create account ...".

Nov 30 20:30:45 Sailfish invoker[3057]: WARNING: requestActivate() called for  QQuickView(0xecf080)  which has Qt::WindowDoesNotAcceptFocus set.
Nov 30 20:30:46 Sailfish dbus-daemon[2390]: invoker: Invoking execution: '/usr/bin/signond'
Nov 30 20:30:47 Sailfish estart[3706]: [W] unknown:0 - writeProfileFile() called, forcing disk write: "/home/nemo/.cache/msyncd/sync/syncemail-23.xml"
Nov 30 20:30:47 Sailfish estart[3706]: [W] unknown:-1 - file:///usr/share/accounts/ui/EmailCryptoSection.qml: File not found
Nov 30 20:30:48 Sailfish mapplauncherd[2408]: Boosted process (pid=7309) was terminated due to signal 11
Nov 30 20:30:48 Sailfish invoker[7519]: error: Can't send signal 11 to application [7309]: No such process
Nov 30 20:30:48 Sailfish systemd[2327]: messageserver5.service: Main process exited, code=killed, status=11/SEGV
Nov 30 20:30:48 Sailfish systemd[2327]: messageserver5.service: Unit entered failed state.
Nov 30 20:30:48 Sailfish systemd[2327]: messageserver5.service: Failed with result 'signal'.
Nov 30 20:30:49 Sailfish estart[3706]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 20:30:49 Sailfish systemd[2327]: messageserver5.service: Service hold-off time over, scheduling restart.
Nov 30 20:30:49 Sailfish systemd[2327]: Stopped messageserver5.
Nov 30 20:30:49 Sailfish systemd[2327]: Starting check accounts for messageserver5...
Nov 30 20:30:49 Sailfish estart[3706]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 20:30:49 Sailfish qmf-accountscheck[7516]: [D] unknown:0 - QMF accounts check: checking email accounts in the system
Nov 30 20:30:49 Sailfish qmf-accountscheck[7516]: [D] unknown:0 - QMF accounts check: found enabled accounts
Nov 30 20:30:49 Sailfish mapplauncherd[2407]: Boosted process (pid=7516) exited with status 0
Nov 30 20:30:49 Sailfish invoker[7979]: invoker: Invoking execution: '/usr/bin/qmf-accountscheck'
Nov 30 20:30:49 Sailfish systemd[2327]: Started check accounts for messageserver5.
Nov 30 20:30:49 Sailfish systemd[2327]: Started messageserver5.
Nov 30 20:30:49 Sailfish estart[3706]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"


While trying to update the mail account the upper bar keeps pulsating forever. Here is the journalctl for that:

Nov 30 21:07:21 Sailfish systemd[2327]: Started check accounts for messageserver5.
Nov 30 21:07:21 Sailfish systemd[2327]: Started messageserver5.
Nov 30 21:07:21 Sailfish dbus-daemon[2390]: dbus-daemon[2390]: [session uid=100000 pid=2390] Activating service name='com.google.code.AccountsSSO.SingleSignOn' requested by ':1.125' (uid=100000 
Nov 30 21:07:22 Sailfish dbus-daemon[2390]: dbus-daemon[2390]: [session uid=100000 pid=2390] Successfully activated service 'com.google.code.AccountsSSO.SingleSignOn'
Nov 30 21:07:24 Sailfish art[3469]: [W] unknown:0 - Unable to allocate new action - oustanding: 2
Nov 30 21:07:24 Sailfish mapplauncherd[2408]: Boosted process (pid=16922) was terminated due to signal 11
Nov 30 21:07:24 Sailfish invoker[18984]: error: Can't send signal 11 to application [16922]: No such process
Nov 30 21:07:24 Sailfish systemd[2327]: messageserver5.service: Main process exited, code=killed, status=11/SEGV
Nov 30 21:07:24 Sailfish systemd[2327]: messageserver5.service: Unit entered failed state.
Nov 30 21:07:24 Sailfish systemd[2327]: messageserver5.service: Failed with result 'signal'.
Nov 30 21:07:24 Sailfish art[3469]: [W] unknown:0 - void EmailAgent::activityChanged(QMailServiceAction::Activity) operation failed error code: 0 error text: "" account: 25 connection status: 0 
Nov 30 21:07:24 Sailfish art[3469]: [W] unknown:0 - Ipc connection not established, can't execute service action
Nov 30 21:07:25 Sailfish syncemail-client[13720]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 21:07:25 Sailfish estart[3706]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 21:07:25 Sailfish art[3469]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 21:07:25 Sailfish systemd[2327]: messageserver5.service: Service hold-off time over, scheduling restart.
Nov 30 21:07:25 Sailfish systemd[2327]: Stopped messageserver5.

**Comment by wdehoog** [comment]
Ok. something went really wrong. With beta 1 on my phone /home/nemo/ does not exist anymore. It is now /home/defaultuser. I have no idea if this is intentional nor how to change your config to use the new path.

**Comment by wdehoog** [comment]
I have updated the [wiki page for troubleshooting](https://github.com/wdehoog/sailfish-bacon-images/wiki/Troubleshooting) to show you how you can 'easily' share a full log.

**Comment by sailorhub77** [comment]
Unfortunately the proposed workaround did not help. I assume it may be a different problem. Both of my email accounts were set to "update every 10 minutes", i.e. the problem described in the link ought not to have been triggered.

By the way, I cannot send emails, either. Try to post two emails caused this journalctl output:

Nov 30 21:50:16 Sailfish mapplauncherd[2353]: Boosted process (pid=4754) was terminated due to signal 11
Nov 30 21:50:16 Sailfish invoker[5181]: error: Can't send signal 11 to application [4754]: No such process
Nov 30 21:50:16 Sailfish systemd[2272]: messageserver5.service: Main process exited, code=killed, status=11/SEGV
Nov 30 21:50:16 Sailfish art[4403]: [W] unknown:0 - void EmailAgent::activityChanged(QMailServiceAction::Activity) operation failed error code: 0 error text: "DNS lookup" account: 8 connec
Nov 30 21:50:16 Sailfish art[4403]: [W] unknown:0 - Error: Send failed
Nov 30 21:50:16 Sailfish systemd[2272]: messageserver5.service: Unit entered failed state.
Nov 30 21:50:16 Sailfish systemd[2272]: messageserver5.service: Failed with result 'signal'.
Nov 30 21:50:17 Sailfish dbus-daemon[2355]: invoker: Invoking execution: '/usr/bin/signond'
Nov 30 21:50:17 Sailfish art[4403]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 21:50:17 Sailfish systemd[2272]: messageserver5.service: Service hold-off time over, scheduling restart.
Nov 30 21:50:17 Sailfish systemd[2272]: messageserver5.service: Start request repeated too quickly.
Nov 30 21:50:17 Sailfish systemd[2272]: messageserver5.service: Unit entered failed state.
Nov 30 21:50:17 Sailfish systemd[2272]: messageserver5.service: Failed with result 'start-limit'.
Nov 30 21:50:17 Sailfish art[4403]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 21:50:17 Sailfish art[4403]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"
Nov 30 21:50:17 Sailfish art[4403]: [W] unknown:0 - void QCopClient::connectToServer() QLocalSocket::ConnectionRefusedError "QLocalSocket::connectToServer: Connection refused"

There was something about DNSlookup in there. So, I tried that. The phone can nmap that server just fine (i.e. resolve its ip). Btw, using that same imap/smtp account from my desktop pc (i.e. from the same public IP address) has not been a problem (just tested that again).

I am, of course, a total layman ("Muggle"), yet, could it be that the messageserver5 cannot establish a socket?

**Comment by wdehoog** [comment]
this seems like a crash ```messageserver5.service: Main process exited, code=killed, status=11/SEGV```
and systemd then decides it has enough of it and does not restart it (start-limit).

can you check with another email account?

**Comment by wdehoog** [comment]
Maybe you can increase logging info wit this: https://sailfishos.org/wiki/Sailfish_OS_Cheat_Sheet#Email_.2F_Active_Sync_.28e-mail.29_debugging

**Comment by sailorhub77** [comment]
Eureka! It's working again!!! Your link was the key after all. There was another posting linked to it which gave me a solution:

https://forum.sailfishos.org/t/setting-up-general-email-imap-smtp-fails/422/18

It was #17 there which did the trick (after an additional reboot).

I am so sorry for "spamming" the issues of your bacon image. As it turns out it was a completely different problem.

Thank you sooo much for your help (and moral support).

**Comment by wdehoog** [comment]
glad it's working for you. could you please close this issue if it remains working?

**Comment by sailorhub77** [comment]
Of course! Again, thanks a million!
