### ISSUE TITLE
About input method

### ISSUE THREAD

**Issue by ghost** [wdehoog/sailfish-bacon-images#5]
Neither Chinese (Pinyin) nor Chinese (Stroke) can be used

**Comment by wdehoog** [comment]
Sorry to hear that. I know nothing of these things related to Sailfish. Could you point me to some more info on how it could work? Like what packages and services are to be used etc.

**Comment by wdehoog** [comment]
Could this be of help to you? Chinese google pinyin keyboard for Sailfish: https://openrepos.net/content/birdzhang/sou-niao-shu-ru-fa-pinyinime

**Comment by tanyongle0633** [comment]
Yes, thank you.

Willem-Jan de Hoog <notifications@github.com> 于 2019年2月25日周一 03:14写道：
