### ISSUE TITLE
Camera not working oneplus one

### ISSUE THREAD

**Issue by liquidlemur** [wdehoog/sailfish-bacon-images#6]
I flashed my Oneplus one with the latest Sailfish OS and the camera doesn't work at all. When I select the camera app, it just shows a black window.

**Comment by wdehoog** [comment]
Hate to say it but it works for me. Anything interesting in the logs (```devel-su journalctl -fa```)?

**Comment by liquidlemur** [comment]
I have the international version of the OPO (A0001) and don't know if that makes a difference? Anyway, thanks for the reply. I'll check the logs when I get back home.

**Comment by wdehoog** [comment]
I have no idea if the OPO version makes any difference. Maybe a specific firmware version? 

Can you switch between front and back camera?

Other log you can try:
```
/usr/libexec/droid-hybris/system/bin/logcat
```
or ```dmesg```

Another camera app to try (maybe give more  logs) https://talk.maemo.org/showpost.php?p=1524623&postcount=128. The version from openrepos.net does not work.

**Comment by liquidlemur** [comment]
One thing I do remember from flashing Sailfish was a mount error.

mount: failed to mount /dev/block/platform/msm_sdcc.1/by-name/userdata at /data: Device or resource busy.

However, when flashing CM-12.1 it mounted fine.

**Comment by liquidlemur** [comment]
> Hate to say it but it works for me. Anything interesting in the logs (`devel-su journalctl -fa`)?

This returned a couple of things (I couldn't login to github from Sailfish to paste any logs)...

Sailfish lipstick[2093]: [D] onTriggered:104 - Application "Camera" with PID 2725 is not responding

Sailfish invoker[4969]: error: Failed to initiate connect on the socket for type silica-media.

Then some bits about an inactive plugin misbehaving.

**Comment by liquidlemur** [comment]
> I have no idea if the OPO version makes any difference. Maybe a specific firmware version?
> 
It has caused install issues with a couple of older custom ROMs.

> Can you switch between front and back camera?
>
No. 
 
> Other log you can try:
> 
> ```
> /usr/libexec/droid-hybris/system/bin/logcat
> ```
I didn't see anything relating to camera
 
> or `dmesg`
>
Nothing here either. Just a lot of stuff about WLAN.
 
> Another camera app to try (maybe give more logs) https://talk.maemo.org/showpost.php?p=1524623&postcount=128. The version from openrepos.net does not work.

Installing this now...

**Comment by liquidlemur** [comment]
> Another camera app to try (maybe give more logs) https://talk.maemo.org/showpost.php?p=1524623&postcount=128. The version from openrepos.net does not work.

No luck. This app just displays the app logo, no camera view.

**Comment by wdehoog** [comment]
Some things:

 * try and see what happens: mk-cam-conf 0 cam-test-0.conf
 * are minimediaservice and miniafservice running? (ps aux)
 * is it a fresh install or an OTA update?

**Comment by liquidlemur** [comment]
> Some things:
> 
>     * try and see what happens: mk-cam-conf 0 cam-test-0.conf
> 
Nothing. No output or anything. It just sits there until I kill it.

>     * are minimediaservice and miniafservice running? (ps aux)
>
Yes.
 
>     * is it a fresh install or an OTA update?

Fresh install, following instructions from https://sailfish-for-opo.tchncs.de/install for the standalone option.

**Comment by wdehoog** [comment]
I don't know what cm12.1 image that points to. You need the one from this repo: https://github.com/wdehoog/sailfish-bacon-images/releases/download/2.0.5.6-b6/cm-12.1-YOG7D-sf-20170218-bacon.zip

Can you strace mk-cam-conf and upload the log or pastebin it somewhere?

```strace  mk-cam-conf 0 cam-test-0.conf > mkcam.log 2>&1```

**Comment by liquidlemur** [comment]
It points to a different CM 12.1. I will try to reflash with the one you linked.

[mkcam.log](https://github.com/wdehoog/sailfish-bacon-images/files/2966659/mkcam.log)

**Comment by liquidlemur** [comment]
Okay, I tried to install your CM 12.1 and it gives me an error.

assert failed: oppo.verify_trustzone("TZ.BF.2.0-2.0.0123") == "1"

**Comment by wdehoog** [comment]
This has something to do with firmware versions. Either the one on your device is too old or too new. 

Unfortunately I know not what to do. On various forums people claim upgrading your recovery would help. I guess we have to do some googling.

For my sailfish images to work you really need this specific CM 12.1 version. It should also be possible to install this CM12.1 standalone (not with sailfish) just for test if it works.

**Comment by wdehoog** [comment]
This one provides links to firmware archives and some tips:
https://forums.oneplus.com/threads/list-oneplus-one-firmwares-modems.421783/

This one has a large collection of firmware archives in one large zip:
https://forum.xda-developers.com/oneplus-one/general/firmware-modem-oneplus-one-t3462214

good luck...

**Comment by liquidlemur** [comment]
Problem is solved. I had to re-flash the factory image (the one that came installed on the phone originally) and then I was able to flash your CM 12.1 without error. Anyway, the camera is working great now! Thanks for your help!

**Comment by wdehoog** [comment]
Great! Where did you get this factory image from?

**Comment by liquidlemur** [comment]
> Great! Where did you get this factory image from?

https://forum.xda-developers.com/oneplus-one/general/guide-return-opo-to-100-stock-t2826541
