### ISSUE TITLE
failure to install sailfish in oneplus one

### ISSUE THREAD

**Issue by jesus6505** [wdehoog/sailfish-bacon-images#7]
I have installed sailfish version 3.0.1.11 and if I do not update it works fine, but if I perform pkcon refresh & update or install a higher version when it restarts, the operating system does not start, staying in the oneplus one logo. It also happens if I install it with multirom

**Comment by wdehoog** [comment]
Hi. 3.0.2.8 has just become available on the build servers. Development has started but is not finished yet. OTA from 3.0.1.11 will indeed not work for now.

**Comment by jesus6505** [comment]
I installed it several times and I never had this. I think that sailfish in some library update or something similar there is something that provokes it. Could you check it?

**Comment by jesus6505** [comment]
How could I send you an image?

**Comment by wdehoog** [comment]
Did you only do pkcon or the whole OTA (ssu release 2.1.3.7 etc.)?
To be honest I am not keen on diving into this. Probably by the end of the week I will have an installable zip for 3.0.2.8 ready.

**Comment by wdehoog** [comment]
@jesus6505 If you want to try I have built an image of 3.0.2.8. It uses local repos (ssu lr) and I did not test much. In theory it should be here https://gofile.io/?c=HruYoX (never used this service).

**Comment by jesus6505** [comment]
/home/geminis/Imágenes/photo_2019-03-31_20-56-21.jpg

**Comment by jesus6505** [comment]
![imagen](https://user-images.githubusercontent.com/47368341/55293924-22aae580-53fc-11e9-82ad-cc3fb42c05d3.png)
he gave me this error

**Comment by jesus6505** [comment]
I downloaded it, I will install it and I will comment

**Comment by wdehoog** [comment]
google says registerauthenticationagentwithoptions is related to policykit. Oulanka changelog mentions some stuff is updated but I can't see a reason why it would not be present.

**Comment by wdehoog** [comment]
Seems indeed something is wrong. The images I have build using the community repos do not start the UI. When retrying to install the first image I made the startup wizard stopped working half way so you end up with a non functioning UI. 

Sorry but I have no idea what could cause this.

**Comment by wdehoog** [comment]
It appears to work much better if I build an older version of libhybris. No idea why this older version 0.0.5.25 (same as for SailfishOS 3.0.1.11) behaves better. The current master branch of libhybris is 0.0.5.30. I'll have to ask the other porters what is going on.

In the mean time if you'd like to give it a try: https://gofile.io/?c=wcjsHY

**Comment by wdehoog** [comment]
I just released the same file as beta 1. The [Oulanka changelog](https://together.jolla.com/question/201103/changelog-302-oulanka/) mention libhybris 0.0.5.25 so I guess it is now as intended.

**Comment by jesus6505** [comment]
Good afternoon, communicate that I have installed version 3.0.2.8 and it works perfectly. Thank you very much and apologize for the inconvenience
