### ISSUE TITLE
Compass does not point north

### ISSUE THREAD

**Issue by sailorhub77** [wdehoog/sailfish-bacon-images#9]
I've been using the lastest release (3.0.3.9 beta 1) and have noticed a slight problem with the compass. It does not seem to point north. I used Aida64 and GPSInfo to verify this. When rotating the phone to 0° (i.e. north), the phone is actually pointing east (which should be 90°).

**Comment by wdehoog** [comment]
Hi. I just installed [OrienteeringCompass](https://openrepos.net/content/ade/orienteeringcompass-scaling-added) from openrepos and it seems to pint in the correct direction.

Mobile phone compasses are not really accurate but indeed 90 degrees is too much off.

**Comment by sailorhub77** [comment]
Thanks for the helpful response. I appreciate it. The outcome with the OrienteeingCompass application was the same for me. However, one thought struck me. How did you hold your phone? When I turn it sideways to landscape mode, it actually points north. But this seems a little unintuitive to me, as I'd expect the phone to be in the "right" orientation with the earpiece pointing up. This was true for the compass in SFOS on the Nexus 5 at least. Am I mistaken?

**Comment by wdehoog** [comment]
I tested it by laying it flat on a table. Just tried vertical position. Still OK. But sometimes whan moving I see a false reading. Even 180 degrees off happens. What does OrienteeringCompass calibration say? On my phone it is 100%.

In file "/etc/sensorfw/primaryuse.conf" there is a section "magnetometer". I doubt it will help but you might try to lookup what the entries mean (I have no idea) and see if modifying them solves your issue.
Sorry but I cannot help you any further.

**Comment by sailorhub77** [comment]
The calibration also claimed to be at 100% on my device. Maybe there is just some hardware issue on my phone.
